server:
  port: 8000

spring:
  datasource:
    url: jdbc:sqlite:DB/ghs.db
    driver-class-name: org.sqlite.JDBC

mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: false